### ISSUE TITLE
Captcha verification empty

### ISSUE THREAD

**Issue by zayn008** [dsoares/roundcube-rcguard#32]
This plugin seems to be installed correctly but when triggered I get a little red message saying 'Captcha verification empty' and no sign of Captcha

**Comment by arafatx** [comment]
For me it said CAPTCHA verification failed! I tried all v2, v3.

**Comment by agabellini** [comment]
Here is the same thing. RC 1.4.3 and rcguard 1.2.2. The log is empty.

**Comment by agabellini** [comment]
Hello,

I solved the problem editing the config.inc.php in the plugin directory. Usually I include my config files outside of the plugin directory,

Andrea

**Comment by dsoares** [comment]
Hi, I'm back to this roundcube plugin repos. If any of you still have this issue, please feel free to reopen it.
I'm using v3 and now i tested the v2, both successfully.

**Comment by arafatx** [comment]
@agabellini I got this issue since february what do you mean editing the config.inc.php 'outside' the plugin? What did you edit in config.inc.php ?

**Comment by agabellini** [comment]
> @agabellini I got this issue since february what do you mean editing the config.inc.php 'outside' the plugin? What did you edit in config.inc.php ?

Hello,

Usually I put all the configuration on the main config.inc.php or in a file included from it. My workaround was to edit the config.inc.php in the plugins/rcguard folder.

The new version solve the problem. Please pay attention when upgrading because the update delete your rcguard plugin config.inc.php. See #37 

Andrea
