### ISSUE TITLE
Plugin not load

### ISSUE THREAD

**Issue by mvldebian** [dsoares/roundcube-rcguard#33]
Setup: RC 1.4.3, PHP 7.2
(Testing with php 7.0 and 7.1 on the same server)

Manual installation, created rcguard folder in plugins
Imported mysql.initial.sql in the roundcube bank
Keys generated in google recaptcha and inserted in the plugin's config

Error log:

`[08-Mar-2020 11:49:29 -0300]: PHP Error: Failed to load plugin file /var/www/roundcube.eth1.com.br/web/plugins/rcguard/rcguard.php in /var/www/clients/client1/web72/web/program/lib/Roundcube/rcube_plugin_api.php on line 174 (POST /?_task=login&_action=login)`

**Comment by arvanus** [comment]
Hi, are you sure you used the correct folders?
Just installed and it worked fine:
git clone https://github.com/dsoares/roundcube-rcguard.git rcguard
mysql -u %%% %%%%%%% -p
cp rcguard/config.inc.php.dist rcguard/config.inc.php
vi rcguard/config.inc.php #Edited keys
vi ../config/config.inc.php # added $config['plugins'][]="rcguard";
and it worded!
Look that you need to have this file: plugins/rcguard/rcguard.php

**Comment by dsoares** [comment]
@mvldebian looking into `program/lib/Roundcube/rcube_plugin_api.php`, that error appears when Roundcube can not read the plugin main file (in this case, the `plugins/rcguard/rcguard.php` file). So i believe your problem was file permissions or ownership, your apache/nginx/... user could not read the file.
Since this was a long time ago, i will close the issue but feel free to reopen it anytime.
