### ISSUE TITLE
config file removed after update

### ISSUE THREAD

**Issue by agabellini** [dsoares/roundcube-rcguard#37]
Hello,

just updated from 1.2.2 to 1.3.1 and my config file was removed.

Before update I edited it and changed $rcmail_config to $config.

Andrea

**Comment by dsoares** [comment]
Hi,
That is a composer issue (composer v2.0 ?). 
If you run `composer update` with the `-vvv` option, you can see composer removing the plugin path and then unarchiving the new version:

    - Upgrading dsoares/rcguard (1.2.2 => 1.3.1): Executing command (CWD): rm -rf '/path_to_my_roundcube/plugins/rcguard'
    Extracting archiveExecuting async command (CWD): unzip -qq  '/path_to_my_roundcube/vendor/composer/tmp-...

It happens with any other plugin. I don't like it either and i'm going to try to find a solution because it does not make any sense.

**Comment by dsoares** [comment]
Update: I did a [PR](https://github.com/roundcube/plugin-installer/pull/27) to roundcube/plugin-installer to address this issue, don't know if it will be accepted. In the meantime, there are 2 possible solutions:
1) use env var `RCUBE_CONFIG_DIR` and use plugin config files like `<plugin_name>.inc.php`
2) use the code from the PR available in my [plugin-installer fork](/dsoares/plugin-installer/tree/keep-plugin-config). I tested it and it works.
